name: docs and package

on:
  push:
    branches: [ main ]


jobs:
  api-website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Set up the Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
   
    - name: Compile project to jar
      run: mvn clean assembly:single
 
    - name: Copy jar to folder
      run: |
        rm -rf jars
        mkdir jars
        cp -rf target/. jars/

    - name: Build docs with Maven
      run: mvn clean javadoc:javadoc

    - name: Copy to Documentation Website Location
      run: |
        rm -rf docs
        cp -rf target/site/apidocs/. docs
    - name: Tidy up the javadocs
      id: tidy
      uses: cicirello/javadoc-cleanup@v1
      with:
        path-to-root: docs
    
    - name: Log javadoc-cleanup output
      run: |
        echo "modified-count = ${{ steps.tidy.outputs.modified-count }}"
    
    - name: Commit documentation changes
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'Endrju00'
          git config --global user.email 'andrzej.kapczynski21@gmail.com'
          git add -A
          git commit -m "Automated API update."
          git push
        fi
